#!/bin/sh
set -e
echo "[start.sh] Node env: $NODE_ENV"
echo "[start.sh] Working dir: $(pwd)"

echo "[start.sh] Listing .medusa root (before start):"
ls -1 .medusa || true

# Verify admin build output at .medusa/client (as generated by `medusa build`)
if [ -f .medusa/client/index.html ]; then
  echo "[start.sh] OK: .medusa/client/index.html exists"
else
  echo "[start.sh] ERROR: missing .medusa/client/index.html – did you run 'npm run build'?"
fi

echo "[start.sh] Short listing .medusa/client:"
ls -l .medusa/client 2>/dev/null | head -20 || true

echo "[start.sh] REDIS_URL length: ${#REDIS_URL}"
echo "[start.sh] MEDUSA_BACKEND_URL: $MEDUSA_BACKEND_URL"

echo "[start.sh] Starting Medusa..."
exec npm run start --silent
